Common:
  device: &device cuda

useRR: false #whether to use rerun for visualization (both offline and rosbag)

Odometry:
  name: MACVO_Mapping
  args:
    # Device directive to the VO system
    # NOTE: the system may not follow this device config strictly since some module
    # e.g. those rely on PWC-Net, only support running on cuda device.
    device: *device
    edgewidth: 32
    num_point: 200 # Upper bound of KPs in each frame

    # Match covariance for keypoint on first observation (sub-pixel uncertainty
    # caused by the quantized pixel)
    match_cov_default: 0.25

    # Profiling the system using torch, generate chrome json trace file.
    profile: false

    # Mapping mode provides the dense mapping
    mapping: 10000
  
    # Online mode does not keep accumulated data inside the VO module.
    online: true

  cov:
    obs:
      type: MatchCovariance
      args:
        device: *device
        kernel_size: 31
        match_cov_default: 0.25
        min_depth_cov: 0.05
        min_flow_cov: 0.25

  keypoint:
    type: CovAwareSelector_NoDepth
    args:
      device: *device
      kernel_size: 7
      mask_width: 32
      max_match_cov: 100.0

  mappoint:
    # Mapping feature can be conveniently turn off by using 
    # "type: NoKeypointSelector" instead of the config below.
    type: MappingPointSelector
    args:
      device: *device
      max_depth: 40  # 5.0
      max_depth_cov: 5 # 0.005
      mask_width: 32

    # type: GridMaxDepthSelector #RandomMaxDepthSelector
    # args:
    #   device: *device
    #   mask_width: 32
    #   max_depth: 40

  frontend:
    # type: CUDAGraph_FlowFormerCovFrontend
    type: FlowFormerCovFrontend
    args:
      device: *device
      weight: /home/tartandriver/tartandriver_ws/src/slam/mac_ros2/Model/MACVO_FrontendCov.pth # ./Model/MACVO_FrontendCov.pth
      enc_dtype: fp16
      dec_dtype: bf16
      decoder_depth: 12
      enforce_positive_disparity: false

  motion:
    type: StaticMotionModel
    args:

  outlier:
    type: CovarianceSanityFilter
    args:
  
  postprocess:
    type: MotionInterpolate
    args:
  
  keyframe:
    type: AllKeyframe
    args:
  
  optimizer:
    type: TwoFrame_PGO
    args:
      device: cpu
      vectorize: true
      parallel: true
      graph_type: disp
      autodiff: false

Preprocess: !include ../mac_slam/Config/Experiment/Common/Preprocess.yaml

Camera:
  fx: 455.7750 
  fy: 456.3191 
  cx: 497.1180 
  cy: 251.8580 
  bl: 0.21     
