# deprecated, not used in offroad.
Common:
  # Some configurations are shared across multiple modules in Odometry, so I write them here.
  device: &device cuda
  max_depth: &max_depth 200

Odometry:
  name: MACVO_Jetson
  args:
    # Device directive to the VO system
    # NOTE: the system may not follow this device config strictly since some module
    # e.g. those rely on PWC-Net, only support running on cuda device.
    device: *device
    edgewidth: 32
    num_point: 200 # Upper bound of KPs in each frame #changed from 200

    # Match covariance for keypoint on first observation (sub-pixel uncertainty
    # caused by the quantized pixel)
    match_cov_default: 10 #0.5 #0.25 #10

    # Profiling the system using torch, generate chrome json trace file.
    profile: false

    mapping: true # Changed

  cov:
    obs:
      type: MatchCovariance #apply exp(*2) before it is filtered, only if not applied, in inference where flow, cov is outputted from model
      args:
        device: *device
        kernel_size: 31
        match_cov_default: 10 #0.5 #10
        min_depth_cov: 0.05
        min_flow_cov: 0.25
        # min_depth_cov: 0.01
        # min_flow_cov: 0.01


  keypoint:
    type: CovAwareSelector #determines odometry
    args:
      device: *device
      kernel_size: 7
      mask_width: 32
      max_depth: *max_depth
      max_depth_cov: 10 #0.5 #250.0
      max_match_cov: 10 #0.5 #100.0
  
  mappoint:
    # type: GridSelector #RandomSelector
    # args:
    #   device: *device
    #   mask_width: 16


    # # type: HybridKeypointSelector
    # # args:
    # #         max_depth: *max_depth
    # #         max_depth_cov: 0.5 
    # #         mask_width: 16
    # #         depth_threshold: 0.5 
    # #         device: *device
        


    type: MappingPointSelector
    args:
      device: *device
      max_depth: 40 # 5.0 #usually tuned
      max_depth_cov: 1000 #0.5 # 0.005 #usually tuned, inkl. max depth
      mask_width: 32

  frontend:
    type: CUDAGraph_FlowFormerCovFrontend
    args:
      device: *device
      weight: /home/tartandriver/tartandriver_ws/src/slam/mac_ros2/Model/MACVO_FrontendCov.pth # Changed from ./model/MACVO_Frontend.pth, for using with ROS node
      dtype: fp32
      max_flow: -1
      enforce_positive_disparity: true # Changed from false

  motion:
    type: StaticMotionModel
    args:

  outlier:
    type: FilterCompose
    args:
      filter_args:
        - type: CovarianceSanityFilter
          args:
        # - type: SimpleDepthFilter
        #   args:
        #     min_depth: 0.05
        #     max_depth: *max_depth
  #       - type: LikelyFrontOfCamFilter
  #         args:
  
  postprocess:
    type: MotionInterpolate
    args:
  
  keyframe:
    type: AllKeyframe
    args:
  
  optimizer:
    type: TwoFramePoseOptimizer
    args:
      device: cpu
      vectorize: true
      parallel: true

Camera:
  # NOTE: Since in zedcam_config.yaml we have down-sampled the image by 4, changed

# From K matrix, color camera
  # fx: 455.77496337890625
  # fy: 456.319091796875
  # cx: 497.1180114746094
  # cy: 251.58502197265625
  
# New from Yifei, vs old from sam

  fx: 455.7750 #477.604949951172  
  fy: 456.3191 #477.604949951172
  cx: 497.1180 #499.5
  cy: 251.8580 #252
  bl: 0.21     #0.209692022937275
